# Generated by Django 4.1 on 2023-05-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='variation',
            field=models.CharField(max_length=15),
        ),
    ]
