# Generated by Django 4.1 on 2023-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='Tembea/services/images')),
            ],
        ),
    ]
